before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: hGnkv4sJpDrHESqsohWCH3W5WBV5GU3umtkZBXPz9b4bWA40bjF8WWNJX7P4sJitJwrLVSf92FeQVWyHRPJ78jnGjVIxmyReVwpeLb9NQdjnabBOXkiiNeLv+FwMiUkFJDcVmdgLI3/TP3EljWCRAutkF6QF5K0G8EqR797iBp1cbgSCBGdDxEbxqU9SIaogirc2X3p3Wt/2lBlX5FiUZNhKlE5LGjjxmngZrsCtLCw9N3nY0uFp1DzHXZj9FY18BVpAwhGYd4hcZzA9PnrWVBrd2RZi6KiZFcV85y6uIeBgM4OzHhD4owpkIvFxJelFZgjWGvnDYpA7pX4GjFgANYzETanlS05CUxqtyd4tp8nwG8bWCJlXEaakLdyjYsuiLrdtEcWmuaBZe7oAocKiJ/vkGeeJJy1hcL1ps+RKPwtLlcoAIJbKmBSJKHeS1BrtRxd03M7Bg2u+AJ1fTXBO/J4ZT1i6fkqlWbKkkpvlP+QDDNlaILiWSyNv8SnRu1kiuK084BNeI7T1cedyUP5E34FbNMl0qyqpQfwjf+yGEMSU+CbWjqqGDXpabNEwSuSzPDYbpp3PB5/gHbQLW/QSafyH+TEx1Z+8CGyNs1gLsTN3g1R+PpNApZSKiHvCJhGuP1n5h2gPMqyyV25Q3dya22mMeyUwPyQ01fiqNNS7Pmw= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
